### ISSUE TITLE
There is no current event loop in thread 'Dummy-1'.

### ISSUE THREAD

**Issue by freeridre** [Develatio/django-walletpass#25]
### Hello!
First of all I would like to thank you this library! Awesome! Unfortunatelly, I have some problems with it.

When I try to use  **pass_instance = builder.write_to_model()** it saves the pass to the DB, but after the push_notification section starts and the problem is that I get this error: **There is no current event loop in thread 'Dummy-1'.**

Somehow, I only get this error on every first or odd attempt. So, when I press the button for the second time, I don't get the error, and I can use the pass. However, when debugging (debugpy), I always get some kind of async thread error, but it seems that the password is being saved to the database correctly. It's just there seems to be some issue with the push_notification.

This is my launch.json
```JSON
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Django",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/passwebservice/manage.py",
            "args": [
                "runserver",
                "192.168.2.17:9090"
            ],
            "django": true,
            "justMyCode": false
        }
    ]
}
``` 
I have a button, which sends a POST request. 
This is my button:
```html
<form method="POST">
        {% csrf_token %}
        <button type="submit" class="image-button">
            <img src="{% static 'images/US-UK_Add_to_Apple_Wallet_CMYK_101421.png' %}" alt="Generate Apple Pass" />
        </button>
</form>
``` 
Currently this is my function which serves the pass generation:
```python
@login_required(login_url='login')
def dashboard_user(request):
    if request.method == "POST":
        builder = PassBuilder(directory = settings.APPLE_PASS_JSON_PATH)
        builder.pass_data_required["serialNumber"] = secrets.token_urlsafe(20)
        builder.pass_data_required["authenticationToken"] = secrets.token_hex(32)
        builder.pass_data["nfc"]["message"] = secrets.token_hex(4)
        pkpass_content = builder.build()

        pass_instance = builder.write_to_model()
        pass_instance.save()
        response = HttpResponse(pkpass_content, content_type="application/vnd.apple.pkpass")
        response['Content-Disposition'] = 'attachment; filename="senity.pkpass"'
        return response

    return render(request, "dashboard.html", {})
``` 

Here is the detailed error message: 
```
Environment:


Request Method: POST
Request URL: https://192.168.2.17/UserHandler/dashboard/

Django Version: 3.2.16
Python Version: 3.7.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'UserHandler',
 'bootstrap5',
 'django_walletpass']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/home/pi/WebService/passwebservice/.venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/pi/WebService/passwebservice/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pi/WebService/passwebservice/.venv/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/pi/WebService/passwebservice/UserHandler/views.py", line 249, in dashboard_user
    pass_instance = builder.write_to_model()
  File "/home/pi/WebService/passwebservice/.venv/lib/python3.7/site-packages/django_walletpass/models.py", line 210, in write_to_model
    instance.data.save(filename, content)
  File "/home/pi/WebService/passwebservice/.venv/lib/python3.7/site-packages/django/db/models/fields/files.py", line 95, in save
    self.instance.save()
  File "/home/pi/WebService/passwebservice/.venv/lib/python3.7/site-packages/django/db/models/base.py", line 740, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/pi/WebService/passwebservice/.venv/lib/python3.7/site-packages/django/db/models/base.py", line 789, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/home/pi/WebService/passwebservice/.venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 182, in send
    for receiver in self._live_receivers(sender)
  File "/home/pi/WebService/passwebservice/.venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 182, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/pi/WebService/passwebservice/.venv/lib/python3.7/site-packages/django_walletpass/signals.py", line 8, in send_push_notification
    instance.push_notification()
  File "/home/pi/WebService/passwebservice/.venv/lib/python3.7/site-packages/django_walletpass/models.py", line 236, in push_notification
    push_module = klass()
  File "/home/pi/WebService/passwebservice/.venv/lib/python3.7/site-packages/django_walletpass/services.py", line 15, in __init__
    self.loop = asyncio.get_event_loop()
  File "/usr/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)

Exception Type: RuntimeError at /UserHandler/dashboard/
Exception Value: There is no current event loop in thread 'Dummy-1'.

``` 
Here is the whole error: [RuntimeError at _UserHandler_dashboard_.pdf](https://github.com/Develatio/django-walletpass/files/13853275/RuntimeError.at._UserHandler_dashboard_.pdf)

I would appreciate if someone could help for me.

**Comment by freeridre** [comment]
oh, I can see that the develop branch is 3 commits ahead then the master branch. Can we get a merge from develop to master?

**Comment by freeridre** [comment]
After I installed the develop branch with pip, now it reversed. I'm able to get the pass in every first time, and somewhy if I cancel to add the pass to my wallet, then in the next pkpass generation I get the same error.

**Comment by freeridre** [comment]
Very strange. Now, it works. With this modification in the PushBackend's class constructor:
```python
class PushBackend:
    def __init__(self):
        try:
            self.loop = asyncio.get_event_loop()
        except RuntimeError:
            self.loop = asyncio.new_event_loop()
            asyncio.set_event_loop(self.loop)
```

**Comment by jefgodesky** [comment]
I'm having the same issue. Do I need to use the `develop` branch for this to work? That seems risky. Will we have a release any time soon with this fix in it?

**Comment by alexandernst** [comment]
I'll release a new version shortly. Haven't got the time yet, sadly
